### ISSUE TITLE
refactor: category 수정, 주석 정리 - [merged]

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_2nd_project_FITinside_frontend#132]
In GitLab by @yooyeonjoo on Oct 14, 2024, 11:59

_Merges feature/category/#31-category -> review-develop_

**Comment by Engineering-Student-An** [comment]
In GitLab by @yooyeonjoo on Oct 14, 2024, 12:00

mentioned in commit 7b678d0bf9e02a4135717002ac28378ddfdcdc8f
