### ISSUE TITLE
fix: Product 관리자 페이지 - [merged]

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_2nd_project_FITinside_frontend#167]
In GitLab by @hahyun on Oct 18, 2024, 01:25

_Merges feature/product/#48-productUpdateImageModify -> review-develop_

- 상품 관리자 페이지 수정
- 상품 수정, 등록할때 이미지 수정, 업로드 가능
- 상품 등록, 수정, 삭제 기능 가능

**Comment by Engineering-Student-An** [comment]
In GitLab by @hahyun on Oct 18, 2024, 01:25

mentioned in commit b19f2522e98ee72f9ac46e464f26a16bfff0acef
