### ISSUE TITLE
Feature/category/#84 category banner feedback - [merged]

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_2nd_project_FITinside_frontend#207]
In GitLab by @yooyeonjoo on Oct 23, 2024, 11:32

_Merges feature/category/#84-categoryBannerFeedback -> review-develop_

**Comment by Engineering-Student-An** [comment]
In GitLab by @yooyeonjoo on Oct 23, 2024, 11:32

mentioned in commit 52d614caede0ecdb0c183827575a64989097c750
