### ISSUE TITLE
fix: 상품 상세 페이지 링크 수정 - [merged]

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_2nd_project_FITinside_frontend#216]
In GitLab by @SubinHeo on Oct 24, 2024, 14:32

_Merges fix/order/#90-orderLinkFix -> review-develop_

**Comment by Engineering-Student-An** [comment]
In GitLab by @SubinHeo on Oct 24, 2024, 14:32

mentioned in commit 864cd8819774634c257b41b6b8101834371763ae
