### ISSUE TITLE
feat: GNB 고정, 모달 등의 제목 고정 기능 추가

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_2nd_project_FITinside_frontend#60]
In GitLab by @anchangmin on Oct 19, 2024, 15:06

- 헤더의 GNB 위치 고정
- 각 페이지, 모달 등의 title 위치 고정 기능 추가

**Comment by Engineering-Student-An** [comment]
In GitLab by @anchangmin on Oct 19, 2024, 17:56

mentioned in commit ac47d3a87d02324a42b9a8438fa4db86db56661c
